name: OCaml CI

on:
  push:
    branches: ['main', 'develop', 'feature/*']
  pull_request:
    branches: ['main', 'develop']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use OCaml 5.1
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "5.1"

    - name: Pin Dune
      run: opam pin add dune https://github.com/ocaml/dune.git

    - name: Install dependencies
      run: dune build @install

    - name: Build
      run: dune build

    - name: Run tests
      run: dune runtest