name: OCaml CI

on:
  push:
    branches: ['main', 'develop', 'feature/*']
  pull_request:
    branches: ['main', 'develop']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use OCaml 5.1
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "5.1"

    - name: Install dependencies
      run: opam install . --deps-only --with-test

    - name: Build
      run: opam exec -- dune build
      
    - name: Run tests
      run: opam exec -- dune runtest